@startuml
start
:Способ задания параметров 
(default = "сначала КО");
if () then ("cначала КО") 
:Кредитная организация;
:Отчетная дта;
else ("сначала Дата")
:Отчетная дата;
:Кредитная организация;
endif
:Готово;
stop 
@enduml
