@startuml
start
:Способ задания параметров 
(default = "сначала КО");
if () then ("cначала КО") 
:Кредитная организация;
:Отчетная дта

(01.01.2024
 04.01.2024 D);
else ("сначала Дата")
:Отчетная дата

(01.01.2024 
 04.01.2024 D);
:Кредитная организация;
endif
:Готово;
stop 
@enduml
