@startuml
start 
floating note right: Процесс стартует каждый час
 if (текущая дата попадает
в период сбора или 
период замен) then (да)
 else (нет)
  if (есть новые отчеты,
которые еще не загружены
в витрину) then (да)
 :загружаем 
 сведения 
 в витрину;
 if (отчет по такой организации,
 на такую отчетную дату
 уже есть в витрине) then (нет)
    
 else (да)
 :обновляем метку
 актуальности 
 для "старой" записи;
 :обновляем сведения 
 об изменениях в данных;
 endif


else (нет)
endif

 endif
end
@enduml