@startuml
start 
floating note right: Процесс стартует каждый час (как проверяем что он ОК, не упал, итп)
 if (текущая дата попадает
в период сбора или 
период замен) then (да)
note right
Для проверки периода
"сбора" или "замен"
создаем/используем
справочник (см. таблица 2)
end note
 else (нет)
  if (есть новые отчеты,
которые еще не загружены
в витрину) then (да)
note right
Новый отчет или нет
определяем по сверке
уникального кода отчета
в  OAD
end note
 :загружаем 
 сведения 
 в витрину;
 if (отчет по такой организации,
 на такую отчетную дату
 уже есть в витрине) then (нет)
 note right
Для формы 202:
отчетная дата; рег. номер головной КО
для формы 202I:
отчетная дата;
для формы 201;
отчетная дата; ТУ
end note
 else (да)
 :обновляем метку
 актуальности 
 для "старой" записи;
 :обновляем сведения 
 об изменениях в данных;
 endif
else (нет)
endif

 endif
end
@enduml