@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "REP_SUBJ" as REP_SUBJ {
    "Кредитные организации"
    --
    *IP_ID <<PK>>
    ... "атрибуты КО"
}
entity "TU_CBR" as TU_CBR {
    "Структурные подразделения Банка России"
    --
    * TU_ID <<PK>>
    ... "атрибуты СПБР"
}
entity "MSR_PRD" as MSR_PRD {
    "Календарь"
    --
    *MSR_PRD_ID <<PK>>
    ... "атрибуты календаря"
}
entity "REP" as REP {
    "Отчеты"
    --
    *REP_ID <<PK>>
    ... "атрибуты отчетов"
}
entity "BO_F0409727_R1" as BO_F0409727_R1{
    "Данные раздела 1"
    --
    REP_ID
    MSR_PRD_ID
    IP_ID
    TU_ID
    "Номер лицевого счета"
    "Полное наименование владельца"
    "Наименования на иностранном языке"
    "Регистрационный номер"
    "TIN"
    "Регистрационный номер в стране регистрации"
    "Регистрационный номер выпуска ценной бумаги"
    "Код ISIN ценной бумаги"
    "Наименование ПФИ"
    "Наименование торговой (биржевой) секции рынка"
    "Код контрагента по ОКСМ"
    "Тип счета"
    "Иная информация"
 }

 entity "BO_F0409727_R1_IS" as BO_F0409727_R1_IS {
    "Код иной секции рынка"
    --
    REP_ID
    MSR_PRD_ID
    IP_ID
    TU_ID
    "Номер лицевого счета"
    "Код иной секции рынка"
    "Наименование иной секции рынка"
 }

 entity "BO_F0409727_R2" as BO_F0409727_R2 {
    "Данные раздела 2"
    --
    REP_ID
    MSR_PRD_ID
    IP_ID
    TU_ID
    "Номер лицевого счета"
    "Дата закрытия счета"

 }
 entity "BO_F0409727_R3" as BO_F0409727_R3{
    " Данные раздела 3"
    --
    REP_ID
    MSR_PRD_ID
    IP_ID
    TU_ID
    "Номер лицевого счета"
    "Дата операционного дня"
    "Сумма входящего остатка руб. коп."
    "Сумма входящего остатка ед. валюты"
    "Сумма оборотов по дебету счета в руб. коп."
    "Сумма оборотов по дебету счета в ед. валюты"
    
 }

REP_SUBJ }|--o{BO_F0409727_R1
REP_SUBJ }|--o{BO_F0409727_R1_IS
REP_SUBJ }|--o{BO_F0409727_R2
REP_SUBJ }|--o{BO_F0409727_R3
MSR_PRD  }|--o{BO_F0409727_R1
MSR_PRD  }|--o{BO_F0409727_R1_IS
MSR_PRD  }|--o{BO_F0409727_R2
MSR_PRD  }|--o{BO_F0409727_R3
REP  }|--o{BO_F0409727_R1 : "REP_ID"
REP  }|--o{BO_F0409727_R1_IS
REP  }|--o{BO_F0409727_R2
REP  }|--o{BO_F0409727_R3


@enduml