@startuml
start
:В МПСО новый "утвержденный" 
и "актуальный" отчет]
if (сейчас период 
"сбора" или "замен") then (да)
:удалить предыдущую версию отчета
из таблицы истории, поступившую
в текущий период сбора или замен;
else (нет)
endif
:загрузить новую версию отчета
в таблицу истории;
end
@enduml
