@startuml
start
:В МПСО новый "утвержденный" 
и "актуальный" отчет]

if  (сейчас период 
"сбора" или "замен" )   then (да)  
:удалить предыдущую версию отчета
из таблицы истории, поступившую
в текущий период сбора или замен; 

else (нет) 
  
note right
Для проверки периода "сбора" или "замен"
создаем/используем//???// справочник
end note

endif 
:загрузить новую версию отчета
в таблицу истории;
note right
  Создаем дополнительную таблицу //BO_NDO_HISTORICAL//
  в которую будем помещать все записи с историей
  предлагаю также предусмотреть что в эту таблицу 
  будем складывать сведения по форме 201 с также
  историей
  ====
  * нужно оценить необходимые мероприятия для 
  построения агрегатов (месяц квартал полугодие год)
  
end note
end
@enduml
